import { motion } from "framer-motion";
import Head from "next/head";
import Navbar from "../components/components/Navbar";
function Contacto() {
  return (
    <motion.div
      initial={{ opacity: 0, backgroundColor: "#FE7A00" }}
      animate={{ opacity: 1, backgroundColor: "#FE7A00" }}
    >
      <Head>
        <title>Metro Clean</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/metro-ico-192" />
      </Head>
      <main>
        <Navbar />
        <div className="layout">
            
        </div>
      </main>
    </motion.div>
  );
}

export default Contacto;
