import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/components/Navbar";
import Features from "../components/sections/Features";
import Hero from "../components/sections/Hero";
import Servicios from "../components/sections/Servicios";
// import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Metro Clean</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/metro-ico-192" />
      </Head>

      <main className="shadow-md bg-primary-500">
        <Navbar />
        <div className="layout">
          <Hero />
          <Features />
          <Servicios />
        </div>
      </main>

      {/* <footer className="bg-primary-500">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={""}>
            <Image
              src="/vercel.svg"
              alt="Vercel Logo"
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer> */}
    </div>
  );
};

export default Home;
