/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": process.env.REGION,
    "aws_appsync_graphqlEndpoint": process.env.APP_END_PNT,
    "aws_appsync_region": process.env.REGION,
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": process.env.API
};


export default awsmobile;
